- hosts: localhost
  vars: 
    - admin_base_url: "http://192.168.99.100:8001"
    - api_base_url: "http://192.168.99.100:8000"
  
  tasks:
    
    - name: Register APIs
      kong_api:
        kong_admin_uri: "{{admin_base_url}}"     
        name: "{{item.name}}"
        upstream_url: "{{item.upstream_url}}"
        request_host: "{{item.request_host}}"       
        state: present
        request_path: "{{item.request_path}}"
      with_items:
        - name: "mockbin"
          upstream_url: "http://gtoms.com"
          request_host: "gtoms.com"
          request_path: "/gtoms"
          strip_request_path: yes
      register: response

    - debug: var=response
